## E-Commerce API ETL Pipeline

#### By Njeri Macharia

### EXTRACT - Get data from an API

- `requests` → talk to APIs

- `url` → API endpoint

- `requests.get(url)` → sends an HTTP GET request

- The API responds with JSON data

- `data = response.json()` Converts the API response into Python objects (lists of dictionaries)

- `df = pd.DataFrame(data)` Turns the JSON into a DataFrame

In [3]:
# importing necessary libraries

import pandas as pd
import requests 
from sqlalchemy import create_engine

#### Structure of JSON Data
Sample Request and API Response

In [5]:
url = "https://fakestoreapi.com/products/1"
response = requests.get(url)
print(response.json())

{'id': 1, 'title': 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 'price': 109.95, 'description': 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', 'category': "men's clothing", 'image': 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png', 'rating': {'rate': 3.9, 'count': 120}}

In [6]:
#extraction

url = "https://fakestoreapi.com/products"
response = requests.get(url)
data = response.json()
df = pd.DataFrame(data)
df

,id,title,price,description,category,image,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'rate': 3.9, 'count': 120}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'rate': 4.1, 'count': 259}"
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'rate': 4.7, 'count': 500}"
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,"{'rate': 2.1, 'count': 430}"
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,"{'rate': 4.6, 'count': 400}"
5,6,Solid Gold Petite Micropave,168.00,Satisfaction Guaranteed. Return or exchange an...,jewelery,https://fakestoreapi.com/img/61sbMiUnoGL._AC_U...,"{'rate': 3.9, 'count': 70}"
6,7,White Gold Plated Princess,9.99,Classic Created Wedding Engagement Solitaire D...,jewelery,https://fakestoreapi.com/img/71YAIFU48IL._AC_U...,"{'rate': 3, 'count': 400}"
7,8,Pierced Owl Rose Gold Plated Stainless Steel D...,10.99,Rose Gold Plated Double Flared Tunnel Plug Ear...,jewelery,https://fakestoreapi.com/img/51UDEzMJVpL._AC_U...,"{'rate': 1.9, 'count': 100}"
8,9,WD 2TB Elements Portable External Hard Drive -...,64.00,USB 3.0 and USB 2.0 Compatibility Fast data tr...,electronics,https://fakestoreapi.com/img/61IBBVJvSDL._AC_S...,"{'rate': 3.3, 'count': 203}"
9,10,SanDisk SSD PLUS 1TB Internal SSD - SATA III 6...,109.00,"Easy upgrade for faster boot up, shutdown, app...",electronics,https://fakestoreapi.com/img/61U7T1koQqL._AC_S...,"{'rate': 2.9, 'count': 470}"
10,11,Silicon Power 256GB SSD 3D NAND A55 SLC Cache ...,109.00,3D NAND flash are applied to deliver high tran...,electronics,https://fakestoreapi.com/img/71kWymZ+c+L._AC_S...,"{'rate': 4.8, 'count': 319}"
11,12,WD 4TB Gaming Drive Works with Playstation 4 P...,114.00,"Expand your PS4 gaming experience, Play anywhe...",electronics,https://fakestoreapi.com/img/61mtL65D4cL._AC_S...,"{'rate': 4.8, 'count': 400}"
12,13,Acer SB220Q bi 21.5 inches Full HD (1920 x 108...,599.00,21. 5 inches Full HD (1920 x 1080) widescreen ...,electronics,https://fakestoreapi.com/img/81QpkIctqPL._AC_S...,"{'rate': 2.9, 'count': 250}"
13,14,Samsung 49-Inch CHG90 144Hz Curved Gaming Moni...,999.99,49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MON...,electronics,https://fakestoreapi.com/img/81Zt42ioCgL._AC_S...,"{'rate': 2.2, 'count': 140}"
14,15,BIYLACLESEN Women's 3-in-1 Snowboard Jacket Wi...,56.99,"Note:The Jackets is US standard size, Please c...",women's clothing,https://fakestoreapi.com/img/51Y5NI-I5jL._AC_U...,"{'rate': 2.6, 'count': 235}"
15,16,Lock and Love Women's Removable Hooded Faux Le...,29.95,100% POLYURETHANE(shell) 100% POLYESTER(lining...,women's clothing,https://fakestoreapi.com/img/81XH0e8fefL._AC_U...,"{'rate': 2.9, 'count': 340}"
16,17,Rain Jacket Women Windbreaker Striped Climbing...,39.99,Lightweight perfet for trip or casual wear---L...,women's clothing,https://fakestoreapi.com/img/71HblAHs5xL._AC_U...,"{'rate': 3.8, 'count': 679}"
17,18,MBJ Women's Solid Short Sleeve Boat Neck V,9.85,"95% RAYON 5% SPANDEX, Made in USA or Imported,...",women's clothing,https://fakestoreapi.com/img/71z3kpMAYsL._AC_U...,"{'rate': 4.7, 'count': 130}"
18,19,Opna Women's Short Sleeve Moisture,7.95,"100% Polyester, Machine wash, 100% cationic po...",women's clothing,https://fakestoreapi.com/img/51eg55uWmdL._AC_U...,"{'rate': 4.5, 'count': 146}"
19,20,DANVOUY Womens T Shirt Casual Cotton Short,12.99,"95%Cotton,5%Spandex, Features: Casual, Short S...",women's clothing,https://fakestoreapi.com/img/61pHAEJ4NML._AC_U...,"{'rate': 3.6, 'count': 145}"

### TRANSFORM

- `df["rating"]` → column with dictionaries

- `.apply()` → run a function on each row

- `lambda` x → each x is one dictionary

- `x["rate"]` → extract the rating value

- `x["count"]` → extract the number of reviews

- Drop the original nested column

In [3]:
#transformation
df["rating_rate"] = df["rating"].apply(lambda x: x["rate"])
df["rating_count"] = df["rating"].apply(lambda x: x["count"])
df = df.drop(columns = ["rating"])
df.head(1)

,id,title,price,description,category,image,rating_rate,rating_count
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,3.9,120

### LOAD - Send data to Postgres

``` python
engine = create_engine(
    "database_type://db_username:db_password@db_location:port/db_name"
)
```

- Create table `products`

- `engine`: the SQLAlchemy connection (Python ↔ Postgres bridge) i.e. connection to the database

- `replace` drops it if it already exists; only for first load, else use `append`

In [4]:
engine = create_engine(
    "postgresql://postgres:new_password@localhost:5433/postgres")

In [5]:
# checking if python connects
engine.connect()

In [6]:
df.to_sql(
    "products",
    engine,
    if_exists = "replace",
    index=False
)

20

### One ETL function, many tables

#### 1. Reusable extractor to get multiple datasets

In [7]:
def extract_from_api(endpoint):
    url = f"https://fakestoreapi.com/{endpoint}"
    response = requests.get(url)

    if response.status_code != 200:
        raise Exception(f"API call failed: {response.status_code}")

    return pd.DataFrame(response.json())

In [8]:
df_products = extract_from_api("products")
df_users = extract_from_api("users")
df_carts = extract_from_api("carts")

In [9]:
df_products.head(3)

,id,title,price,description,category,image,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'rate': 3.9, 'count': 120}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'rate': 4.1, 'count': 259}"
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'rate': 4.7, 'count': 500}"

In [10]:
df_users.head(3)

,address,id,email,username,password,name,phone,__v
0,"{'geolocation': {'lat': '-37.3159', 'long': '8...",1,john@gmail.com,johnd,m38rmF$,"{'firstname': 'john', 'lastname': 'doe'}",1-570-236-7033,0
1,"{'geolocation': {'lat': '-37.3159', 'long': '8...",2,morrison@gmail.com,mor_2314,83r5^_,"{'firstname': 'david', 'lastname': 'morrison'}",1-570-236-7033,0
2,"{'geolocation': {'lat': '40.3467', 'long': '-3...",3,kevin@gmail.com,kevinryan,kev02937@,"{'firstname': 'kevin', 'lastname': 'ryan'}",1-567-094-1345,0

In [11]:
df_carts.head(3)

,id,userId,date,products,__v
0,1,1,2020-03-02T00:00:00.000Z,"[{'productId': 1, 'quantity': 4}, {'productId'...",0
1,2,1,2020-01-02T00:00:00.000Z,"[{'productId': 2, 'quantity': 4}, {'productId'...",0
2,3,2,2020-03-01T00:00:00.000Z,"[{'productId': 1, 'quantity': 2}, {'productId'...",0

#### 2. Table-specific transformations

##### Products Table

In [12]:
def transform_products(df):
    
    # Rating
    df["rating_rate"] = df["rating"].apply(lambda x: x["rate"])
    df["rating_count"] = df["rating"].apply(lambda x: x["count"])
    df.drop(columns=["rating"], inplace=True)
    return df

##### Users Table

In [13]:
def transform_users(df):
    
    # Name
    df["fname"] = df["name"].apply(lambda x: x["firstname"])
    df["lname"] = df["name"].apply(lambda x: x["lastname"])

    # Address 
    df["city"] = df["address"].apply(lambda x: x["city"])
    df["street"] = df["address"].apply(lambda x: x["street"])
    df["street_number"] = df["address"].apply(lambda x: x["number"])
    df["zipcode"] = df["address"].apply(lambda x: x["zipcode"])
    df["lat"] = df["address"].apply(lambda x: x["geolocation"]["lat"])
    df["long"] = df["address"].apply(lambda x: x["geolocation"]["long"])

    # Cleanup 
    df.drop(columns=["name", "address", "__v"], inplace=True)

    return df

##### Cart Table

In [14]:
def transform_carts(df):
    
    df = df.copy()
    
    # Date
    df["date"] = pd.to_datetime(df["date"])

    # Cleanup
    df.drop(columns=["__v", "products"], inplace=True)

    return df

In [15]:
def create_cart_items(df):
    
    # Products
    cart_items = df[["id", "products"]].explode("products")

    cart_items["product_id"] = cart_items["products"].apply(lambda x: x["productId"])
    cart_items["quantity"] = cart_items["products"].apply(lambda x: x["quantity"])

    cart_items.rename(columns={"id": "cart_id"}, inplace=True)

    cart_items.drop(columns=["products"], inplace=True)

    return cart_items

#### 3. Generic loader (same for ALL tables)

In [16]:
# fakestore db
engine = create_engine(
    "postgresql://postgres:new_password@localhost:5433/postgres")
engine.connect()

In [17]:
# Load function

def load_to_postgres(df, table_name, engine):
    df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
    )

#### 4. Orchestration

In [18]:
# Dictionary of table names and transform functions
tables = {
    "products": transform_products,
    "users": transform_users,
    "carts": transform_carts
}

# ETL for products, users, carts
for table, transform_fn in tables.items():
    df = extract_from_api(table)      # Extract
    df = transform_fn(df)             # Transform
    load_to_postgres(df, table, engine)  # Load

# Special case: cart_items (derived from carts)
df_carts_raw = extract_from_api("carts")
df_cart_items = create_cart_items(df_carts_raw)
load_to_postgres(df_cart_items, "cart_items", engine)